name: Metrics
on:
  # Schedule
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          
          token: ${{ secrets.METRICS_TOKEN }}

          # Settings
          user: L33tSh4rk
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Visual
          config_display: large
          theme: dark
          
          # PLUGIN: ISOCALENDAR
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # PLUGIN: LANGUAGES 
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%

          # Privacy Settings
          committer_token: ${{ secrets.METRICS_TOKEN }}
