name: Metrics
on:
  # Schedule
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          
          # Settings
          user: L33tSh4rk
          base: activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          config_display: large

          # INTRODUCTION
          plugin_introduction: yes
          
          # ISOCALENDAR
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # LANGUAGES 
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%

          # FOLLOWUP
          plugin_followup: yes
          plugin_followup_sections: closed
          plugin_followup_indepth: yes

          # Privacy
          committer_token: ${{ secrets.METRICS_TOKEN }}
