name: Metrics
on:
  # Schedule
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          extras_css: |
            svg { background-color: #1a1b26 !important; border-radius: 4px; }
            .header { color: #7aa2f7 !important; }
            .field { color: #c0caf5 !important; fill: #c0caf5 !important; }
            .calendar .contribution { fill: #9ece6a !important; }
            
          # Settings
          user: L33tSh4rk
          base: header, activity, community, metadata
          config_timezone: America/Sao_Paulo
          config_display: regular
          
          # ISOCALENDAR
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # LANGUAGES 
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%

          plugin_followup: yes
          plugin_followup_sections: closed

          # Privacy
          committer_token: ${{ secrets.METRICS_TOKEN }}
